// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    id,
    name,
    description,
    amount_of_employees,
    registered,
    type
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, amount_of_employees, registered, type, created_at, updated_at
`

type CreateCompanyParams struct {
	ID                pgtype.UUID
	Name              string
	Description       pgtype.Text
	AmountOfEmployees int32
	Registered        bool
	Type              string
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.AmountOfEmployees,
		arg.Registered,
		arg.Type,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AmountOfEmployees,
		&i.Registered,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :execrows
DELETE FROM companies
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompany, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, description, amount_of_employees, registered, type, created_at, updated_at
FROM companies
WHERE id = $1
`

func (q *Queries) GetCompany(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompany, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AmountOfEmployees,
		&i.Registered,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const patchCompany = `-- name: PatchCompany :one
UPDATE companies
SET
    name = COALESCE($1::text, name),
    description = COALESCE($2::text, description),
    amount_of_employees = COALESCE(
        $3::integer,
        amount_of_employees
    ),
    registered = COALESCE(
        $4::boolean,
        registered
    ),
    type = COALESCE(
        $5::text,
        type
    ),
    updated_at = NOW()
WHERE id = $6::uuid
RETURNING id, name, description, amount_of_employees, registered, type, created_at, updated_at
`

type PatchCompanyParams struct {
	Name              pgtype.Text
	Description       pgtype.Text
	AmountOfEmployees pgtype.Int4
	Registered        pgtype.Bool
	Type              pgtype.Text
	ID                pgtype.UUID
}

func (q *Queries) PatchCompany(ctx context.Context, arg PatchCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, patchCompany,
		arg.Name,
		arg.Description,
		arg.AmountOfEmployees,
		arg.Registered,
		arg.Type,
		arg.ID,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.AmountOfEmployees,
		&i.Registered,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
